<div class="page-content">
    <div class="container-sm">
        <h4 class="">Momentum Biotechnologies Privacy Policy</h4>
        <p>
        PureHoney Technogies, Inc., d/b/a Momentum Biotechnologies (the "Company", "we", or "us") is commit-ted to respecting and protecting your personal privacy.  This Privacy Policy, including any future modifica-tions and/or addenda (collectively, this "Privacy Policy") applies to all information (including personal in-formation) we may collect through your use of momentum.bio (the "Site"), any information you provide to us voluntarily, and any other sites, applications (or "apps"), software, studies or content offered by the Com-pany from time to time that link or otherwise refer to this Privacy Policy (collectively, including the Site, the "Services").  This Privacy Policy is effective with respect to all information we have collected from you or will collect from you in the future. <br><br>
        </p>
        <h4 class="">What type of information do we collect and how do we collect it?</h4>
        <p>
        General Categories:  We receive, collect and store information you enter on our Site or provide to us in any other way, including information that relates to, describes, is capable of being associated with, or could rea-sonably be linked, directly or indirectly, with a particular individual or household (“Personal Information”).   In general, this may include the following categories of Personal Information:
        </p>
        <ul>
            <li><b>Identifiers:</b>  Examples might include your name, email address, phone number, IP address, device identifier, or account name;</li>
            <li><b>Personal Information:</b>  Examples might include your business information;</li>
            <li><b>Commercial Information:</b>  Examples might include the products or Services you've purchased from us or engaged us to perform for you, and other purchasing histories or tendencies;</li>
            <li><b>Biometric Information:</b>  Examples might include genetic information;</li>
            <li><b>Internet Activity:</b>  Examples might include your browsing history, your search history, and information on your interaction with the Site and the Company's advertisements, page response times, length of visits to certain pages, page interaction information, and methods used to browse away from the page;
            </li>
            <li><b>Geolocation Data:</b>  Examples might include your physical location;</li>
            <li><b>Professional or Employment-Related Information:</b>  Examples might include your employer, job posi-tion, salary, etc.; and</li>
            <li><b>Inferences:</b>  The Company may make inferences drawn from other personal information listed above, to create a profile reflecting your preferences, characteristics, psychological trends, predispositions, be-havior, attitudes, intelligence, abilities, and/or aptitudes</li>
        </ul>
        <p>Information you provide to us:  When you access, register, use, subscribe to, or purchase our Services, purchase a product, communicate with us, upload other information, submit a request online,(e.g., a request through customer services), or otherwise communicate with us, directly or through a third party, we may collect and store any personal information you provide.    This information may include, without limitation, your: Personal Information, e-mail communications; phone communications; messaging platform communi-cations; data entered into forms or surveys; dates and times of access, usernames; passwords; web cook-ies; or other user-generated content that you disclose to us, payment information, and any information you provide to us about other people.  By submitting such information, you agree it may be shared by the Com-pany with third parties for the purposes detailed in this Privacy Policy.<br><br>
        <u>Information about your use of the Services:</u>  The Site may use cookies and other means of collecting in-formation.  Cookies are messages placed on your computer or mobile device when you visit a website or page.  A cookie may be used to store your login and profile details so you do not have to re-enter them each time you login.  It is possible to disable the placement of cookies through your browser set-tings.  However, as portions of the Site rely on cookies to enable certain functionality, if you choose to dis-able cookies, some of this functionality may not work properly.<br><br>
        The Site uses cookies, web beacons, pixels, and other tracking technologies to collect information about your use of the Site, including without limitation, your browser type and version, IP address, operating sys-tem and platform, when you open email that we send you, and other similar information.<br><br>
        We may also use cookies to deliver ads, record user-specific information on what pages users access or visit, and track and record past activity at the Site. <br><br>
        We may collect and store information locally on your device using mechanisms such as browser web stor-age and application data caches.  In addition, if you access the Site from a mobile or other device, we may collect a unique device identifier assigned to that device, geolocation data (including your precise location), or other transactional information for that device.  If you telephone us, or if we call you, the call may be recorded.  Online interactions may also be recorded.<br><br>
        <u>Information from other sources:</u>  We may obtain additional Personal Information about you from our service providers, customers, agencies, the internet, offline sources, or other public or commercial sources includ-ing, but not limited to, social media services to which you have provided Personal Information.  When you access the Services through a third-party service (e.g., Facebook, Twitter, etc.), you connect the Services to a third-party service, or share our content via a third-party service, you are authorizing us to collect, store, and use such information and content in accordance with this Privacy Policy.<br><br>
        We may also receive additional Personal Information about you from certain third parties (e.g., researchers or analysts) that provide us with statistical, demographic, or other similar information.  Further, we may combine your online information with information we obtain from offline sources, including, without limitation, information that you may provide us with over the phone or via email.  <b>The Company is not responsible for the privacy practices of third parties.</b> </p>
        <h4>How does the Company use your information?</h4>
        <p>
        The Company may use your information, including your Personal Information, to provide and improve our Services.  Specifically, the Company may use your Personal Information for the following purposes:<br>
        1.	To provide, personalize and operate the Services for you;<br>
        2.	To provide you with ongoing customer assistance and technical support;<br>
        3.	To maintain, measure, enhance, and otherwise improve our Services;<br>
        4.	To provide you with requested information and services; <br>
        5.	To develop new services; and<br>
        6.	To comply with any applicable laws and regulations.<br>

        <br>
        The Company may use your Personal Information to send you information about your account, the Services or other services, upcoming events, and to notify you about issues with or changes to the Services. From time to time, we may use your information to send important notices, such as communications about changes to our terms, conditions, and/or policies. We may also make various email series and one-time emails available to recipients in our database to help them get the most value from our Services. Such emails include, but are not limited to, service updates and educational materials from the Company and/or its service providers.<br><br>
        We may use your information to provide technical support and assistance for the Services, depending on the specific Service, via telephone, text, e-mail, instant message, or another online platform.  Your infor-mation may be used to fulfill any other purpose for which you provide information or otherwise provide your consent for the Company and/or other third parties to use such information.  <br><br>
        The Company may aggregate and/or anonymize any information collected for various purposes. Once ag-gregated or anonymized, the information will no longer be considered "personal information" because it will no longer be able to identify you and/or any of your specific devices used to access the Services. The Company may use such information for any purpose (e.g., research and development purposes), including sharing such information with third parties.</P>
        <h4>How does the Company store, share and disclose your Personal Information?</h4>
        <p>
        The Site is hosted on the Wix.com platform. Wix.com provides us with the online platform that allows us to market our products and services to you. Your Personal Information may be stored through Wix.com’s data storage, databases and the general Wix.com applications. Your Personal Information is stored on secure servers behind a firewall.  We may share your Personal Information to allow our service providers and other third parties, including Wix.com, to assist in providing and managing the Services.<br><br>
        Sharing your Personal Information may be necessary to facilitate the day-to-day operation of our business, to allow our service providers and other third parties assist in providing and managing the Services, and to allow for business planning for strategic growth.  This may include sharing information with internal stake-holders; implementing training procedures; planning and allocating resources and budgets; performing data modelling; facilitating internal reporting; and analyzing growth strategies.<br><br>
        The Company may share your Personal Information as necessary to allow for the backup and protection of your information (e.g., utilizing cloud-based services to archive/protect data) in order to ensure that such information is not improperly lost or modified. Such sharing may also be necessary to archive/protect data, including Personal Information, in accordance with legal, regulatory, organizational, and/or contractual obli-gations.<br><br>
        The Company is part of industry self-regulatory organizations.  Such organizations were formed to address various concerns, including: developing industry standards and best practices to protect the industry; shar-ing intelligence or concerns about individuals (e.g., industry-specific watch lists); sharing intelligence or concerns that may have a negative or detrimental impact on the industry; and/or ensuring that participants in the industry are following agreed-upon standards. The Company may be required to share Personal In-formation as required to stay in compliance with these self-regulatory requirements.</p>
        <h4>How do we communicate with you?</h4>
        <p>
        We may contact you to respond to your inquiry or answer technical questions, to send updates about the Company, or as otherwise necessary to contact you to enforce our User Agreement, applicable national laws, and any agreement we may have with you. For these purposes we may contact you via email or phone.</p>
        <h4>How can you withdraw your consent?</h4>
        <p>
        If you want us to stop processing your information, including Personal Information, or if you would like to access, correct, amend or delete any of your Personal Information that we have about you, please contact us at: info@momentum.bio or send us mail to: Momentum Biotechnologies, 3 Federal St. Suite 300, Billeri-ca, MA 01821, USA.  </p>
        <h4>Privacy policy updates</h4>
        <p>We reserve the right to modify this Privacy Policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the Site. If we make material changes to this Privacy Policy, we will notify you <a href="">here</a> that it has been updated. </p>
        <h4>Questions and our contact information</h4>
        <p>If you have any questions about this Privacy Policy, you are invited to contact us at: info@momentum.bio or send us mail to: Momentum Biotechnologies, 3 Federal St. Suite 300, Billerica, MA 01821, USA.</P>
        <p>
            <b>LAST UPDATED:  February 8, 2023</b>
        </p>
    </div>
</div>